info:
  app:
    name: Spring Boot App

server:
  error:
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always